name: 手动构建可执行文件

on:
  workflow_dispatch:

jobs:
  build:
    name: 构建于 ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-20.04, debian-arm64 ]
        include:
          - os: debian-arm64
            dist: bookworm
            arch: arm64
       
    steps:
      - name: 签出存储库
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        if: runner.os != 'debian-arm64'

      - name: 在 Debian ARM64 上安装依赖项
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install pyinstaller
        if: runner.os == 'debian-arm64'

      - name: 构建 Win 可执行文件
        if: runner.os == 'Windows'
        run: |
          pyinstaller --icon=./static/images/TikTokDownloader.ico --add-data "static:static" --add-data "locale:locale" --add-data "templates:templates" --collect-all emoji main.py
        shell: pwsh

      - name: 构建 Linux ARM64 可执行文件
        if: runner.os == 'debian-arm64'
        run: |
          pyinstaller --add-data "static:static" --add-data "locale:locale" --add-data "templates:templates" --collect-all emoji main.py

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: TikTokDownloader_${{ runner.os }}_${{ runner.arch }}
          path: dist/main/
